### ISSUE TITLE
New IGC spec breaks HFDTE format

### ISSUE THREAD

**Issue by johnstevenson** [vicb/VisuGps#11]
Hi,
The new IGC specification ( http://www.fai.org/downloads/igc/FRTS_4 )  breaks the HFDTE format by changing it to ```HFDTEDATE:DDMMYY,NN```

Essentially all H-records are formatted the same now (ie name and value separated by a colon) because the HFFXA record has been dropped. Note that the ```,NN``` part is the flight number on the day and is optional for Non-IGC FRs (though they forgot to mention that).

I provided manolis with some patches for Leonardo, which included your ```vg_parser.php```. I changed the regex at line 57 to handle this:

```php
    if (preg_match('/(?:HFDTE(?:DATE:)?)(\d{2})(\d{2})(\d{2})/mi', $trackFile, $m)) {
        $trackData['date']['day'] = intval($m[1]);
        $trackData['date']['month'] = intval($m[2]);
        $trackData['date']['year'] = intval($m[3]) + (($m[3] > 60)?1900:2000);
    }
```
Rather than do a PR, I am reporting it here as ```BlueGps.java``` will also need modifying.

**Comment by vicb** [comment]
@johnstevenson thanks for the issue.

Could you please submit a PR with the change in `vg_parser.php`. I don't think `BlueGps` need to be modified, it's only used to simulate a GPS for live tracking.
